#!/bin/bash

# opencocon CD creator

export FLAVOR="thinclient"


if [ ! "`echo $SYSLINUX_BIN_PATH`" ];
then
  SYSLINUX_BIN_PATH="/usr/lib/syslinux/"
fi


if [ ! "`echo $ISOLINUX_PATH`" ];
then
  ISOLINUX_PATH="/usr/lib/ISOLINUX/"
fi


if [ $3 ];
then

  if [ ! "`which genisoimage`" ];
  then
    echo "Error: genisoimage is not found."
    exit 2
  fi

  
  # Create work directory
  CURPWD=`pwd`
  IMAGE_DATE=`date +%Y%m%d`
  WORKDIR="$CURPWD/image-$IMAGE_DATE"
  mkdir -p $WORKDIR/isolinux/

  # Copy isolinux
  if [ ! -r $ISOLINUX_PATH/isolinux.bin ];
  then
    echo "Error: isolinux.bin is not found. Please specify SYSLINUX_BIN_PATH."
    exit 2
  fi

  cp -L $ISOLINUX_PATH/isolinux.bin  $WORKDIR/isolinux/isolinux.bin
  cp -L $SYSLINUX_BIN_PATH/modules/bios/menu.c32  $WORKDIR/isolinux/menu.c32
  cp -L $SYSLINUX_BIN_PATH/modules/bios/ldlinux.c32 $WORKDIR/isolinux/ldlinux.c32

  # Copy image to work directory
  if [ ! -r $1/bzImage-cocon486.bin ];
  then
    echo "Error: bzImage-cocon486.bin is not found."
    exit 2
  fi

  cp -L $1/bzImage-cocon486.bin  $WORKDIR/bzImage

  if [ ! -r $1/opencocon-cocon486.squashfs ];
  then
    echo "Error: opencocon-cocon486.squashfs is not found."
    exit 2
  fi

  cp -L $1/opencocon-cocon486.squashfs  $WORKDIR/crusoe.sqs


  if [ ! -r $1/initramfs-crusoe-image-cocon486.squashfs ];
  then
    echo "Error: initramfs-crusoe-image-cocon486.squashfs is not found."
    exit 2
  fi

  cp -L $1/initramfs-crusoe-image-cocon486.squashfs  $WORKDIR/early.sqs


  # Copy some file from define directory
  cp -RL $2/*  $WORKDIR/


  # Create CD image
  iso_filename="$CURPWD/opencocon-$FLAVOR-$3-$IMAGE_DATE.iso"
  genisoimage -v -r -J -o $iso_filename -b isolinux/isolinux.bin -no-emul-boot -boot-load-size 4 -boot-info-table -A OPENCOCON $WORKDIR/
  isohybrid --ctrlhd0 $iso_filename

  if [ ! -r "$iso_filename" ];
  then
    echo "Error: genisoimage failed."
    exit 2
  fi
  cd $CURPWD
  md5sum $iso_filename > "${iso_filename}.md5"


else
  echo "usage: cocon-cdcreator [deploy image path] [define dir] [version]"
fi


